# Generated by Django 5.0.2 on 2024-02-16 11:54

import api.models.auth
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiry_date', models.DateTimeField(default=api.models.auth.default_expiry)),
                ('is_used', models.BooleanField(default=False)),
                ('permanent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('authtoken.token', models.Model),
        ),
    ]
